services:
  spring-app:
    build: .
    ports:
      - "9060:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_directory
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3307:3306"

    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d